[firebase]
type = "service_account"
project_id = "bhalani-55bb4"
private_key_id = "f36043a6288f73f0962059673bb4e1894b0e7343"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDRbM5YYS4W0+rC
9XD66xoo0/YwE/f9b1rPNLPs8cpCYNabJPZKLaoY68gdioWX2x3rmft+0aGBT3S4
KxuUMEF1+rCtaapABwAJgPwcmbykL3jnblsPsnjM78uWXaCHVGrgjCdn2Wbwnqkz
F8svU5l8kWUULtfNnZ+D346KrGZa3s5XkB4FzH1EkoRhs3nIm6dInLLrPwWjF0so
HUcSl9au2cBrh/rpiMTGd5LJM5aKgT/kthaB/7AE43jR9ikaV7LbaueisW+5KSze
3JOqOU/lILmLzcf6tyy2WZ3pRYnUhE0auJ3rbh03apYNP9L/6r48vEddo/JxubuF
CpQJUjpxAgMBAAECggEAAbmyssLUtFCRRWNMJ64QjmvuIh/k/fYZFn5PuezVSrIV
bIxruMla5pcJNFiaAIn4K3LuofEoUmpZGuQUh2ZVILuksV4OrnW8Tee9k/7+gVAI
kAgOSSEiWoZifBH4Bstm0MQo1jPB48s718FbPb/joqWIQpf+9ElHWVjZ+dmhI4Ag
+shHX+YiImFW0D188WqFlSmM439+N3R89egZTC7TVcvUQRSPKq0nA17YUx5sDoSX
JB561rFAiBFoUjkS5kp0Z+0YdqPJTiE61nr67tLFvoyXrDv8G5ojRX3wBttVDI0b
YL2d7F53pNVnuaRwmgEgdIfEBpj45LsR1VJUifJHIQKBgQD1ns7vsZPYRRmGF/9N
j7WUwEo63eKVnEMmp0zgPY6mrB6Nm9zesQWihlL+6fbVqQWsBUVmXC02E4AUEZIS
t31/Li1nwBFZPmA8MfnuDpLXnhhIcjA4sDP9m4KjxsQ8O30LIypG4ObbUs8PhMw/
jY2GN028GyqsGugRPi6Cz8tN4QKBgQDaRm0gYF33ZqrkeDQKmsOFVSRdiYzQxgrq
NKECr+B+J5N+86wPVlHpjTn4FBquW+Lr7o4TEfRjkP2+1VyXadNw7OvDwHz4FhM+
3b9lIXb3MQiiBHi9zauiQbVGgf2KORdpZFdpVNczhsQYTh1YvY2wI28rV897STwi
0P2eaeLekQKBgQDLGuxBttTrpJArm1JpH6nmfG+lZ+/DCXlZ0EQ4tY5tcqy9KqKk
nztqnqqo0m1jVqYzDhTKRPS537wsXC8vPP4Qme2/+koeQv8vJ6BlYzW4CKpJ1erc
JZCIaPzJU0bYC9UlzYlbHQSpXjuMuKJw9yuNTdQA9XH+6Sz3fTTWxN934QKBgQCB
sFSIZxmNtH+XLeBl6JyBLRxlQyPaq8CydUCxUwSEkEkvpeI2Xqhepx2pS3Cq5keG
vP/HTuSw/+X0K9tOz37k2rAeZ9EYqi0XLjPZB7AioQyrDxMaWwg+aOInGXcmWFOT
uB3DpLgUkl8Svd7r6fw0imk0DIFnlBTZ7uix5eH5MQKBgFKFTbpZ4a2TbghzjRG8
gVDZgw9GpGNqrKffcbJg/77zJVTyQAnefyCPzzyjIw5LHPUQynA9OBTz5X/CM2/K
achRmGPsFqMOh5om5L9uTAhcdiUjQ+WaFBsCuQJ2LA4fCJp7DPUXAQqUDfoI1mG4
AssNuaKkiklWd1RJS0rOgugg
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@bhalani-55bb4.iam.gserviceaccount.com"
client_id = "112015284958601078276"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/your-service-account-email%40appspot.gserviceaccount.com"
database_url = "https://bhalani-55bb4-default-rtdb.firebaseio.com/"

api_key = "AIzaSyCVKlqf_11Hv5uC8E1hRvHAdRfXWkCeXEo"
auth_domain = "bhalani-55bb4.firebaseapp.com"
storage_bucket = "bhalani-55bb4.firebasestorage.app"
messaging_sender_id = "284474094887"
app_id = "1:284474094887:web:e10947e4c48fb537376502"
measurement_id = "G-3JC64LGGTJ"
