[firebase_client]
api_key = "AIzaSyCVKlqf_11Hv5uC8E1hRvHAdRfXWkCeXEo" # Changed to snake_case
auth_domain = "bhalani-55bb4.firebaseapp.com"       # Changed to snake_case
database_url = "https://bhalani-55bb4-default-rtdb.firebaseio.com" # Changed to snake_case
project_id = "bhalani-55bb4"                         # Changed to snake_case
storage_bucket = "bhalani-55bb4.firebasestorage.app" # Changed to snake_case
messaging_sender_id = "284474094887"                 # Changed to snake_case
app_id = "1:284474094887:web:e10947e4c48fb537376502"  # Changed to snake_case
measurement_id = "G-3JC64LGGTJ"                      # Changed to snake_case
# --- Google OAuth Client ID (for streamlit-google-auth) ---
[google_oauth]
client_id = "284474094887-41hqm10ikn8t53d7lv69735ke47qo6e2.apps.googleusercontent.com"
client_secret = "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"

# You might also need to explicitly list the redirect_uri if the component requires it
# redirect_uri = "https://your-app-name.streamlit.app"
