

[firebase]
type = "service_account"
project_id = "bhalani-55bb4"
private_key_id = "f36043a6288f73f0962059673bb4e1894b0e7343"
# ENSURE THIS PRIVATE KEY IS EXACTLY AS SHOWN, WITH ESCAPED NEWLINES
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDRbM5YYS4W0+rC\n9XD66xoo0/YwE/f9b1rPNLPs8cpCYNabJPZKLaoY68gdioWX2x3rmft+0aGBT3S4\nKxuUMEF1+rCtaapABwAJgPwcmbykL3jnblsPsnjM78uWXaCHVGrgjCdn2Wbwnqkz\nF8svU5l8kWUULtfNnZ+D346KrGZa3s5XkB4FzH1EkoRhs3nIm6dInLLrPwWjF0so\nHUcSl9au2cBrh/rpiMTGd5LJM5aKgT/kthaB/7AE43jR9ikaV7LbaueisW+5KSze\n3JOqOU/lILmLzcf6tyy2WZ3pRYnUhE0auJ3rbh03apYNP9L/6r48vEddo/JxubuF\nCpQJUjpxAgMBAAECggEAAbmyssLUtFCRRWNMJ64QjmvuIh/k/fYZFn5PuezVSrIV\nbIxruMla5pcJNFiaAIn4K3LuofEoUmpZGuQUh2ZVILuksV4OrnW8Tee9k/7+gVAI\nkAgOSSEiWoZifBH4Bstm0MQo1jPB48s718FbPb/joqWIQpf+9ElHWVjZ+dmhI4Ag\n+shHX+YiImFW0D188WqFlSmM439+N3R89egZTC7TVcvUQRSPKq0nA17YUx5sDoSX\nJB561rFAiBFoUjkS5kp0Z+0YdqPJTiE61nr67tLFvoyXrDv8G5ojRX3wBttVDI0b\nYL2d7F53pNVnuaRwmgEgdIfEBpj45LsR1VJUifJHIQKBgQD1ns7vsZPYRRmGF/9N\nj7WUwEo63eKVnEMmp0zgPY6mrB6Nm9zesQWihlL+6fbVqQWsBUVmXC02E4AUEZIS\nt31/Li1nwBFZPmA8MfnuDpLXnhhIcjA4sDP9m4KjxsQ8O30LIypG4ObbUs8PhMw/\njY2GN028GyqsGugRPi6Cz8tN4QKBgQDaRm0gYF33ZqrkeDQKmsOFVSRdiYzQxgrq\nNKECr+B+J5N+86wPVlHpjTn4FBquW+Lr7o4TEfRjkP2+1VyXadNw7OvDwHz4FhM+\n3b9lIXb3MQiiBHi9zauiQbVGgf2KORdpZFdpVNczhsQYTh1YvY2wI28rV897STwi\n0P2eaeLekQKBgQDLGuxBttTrpJArm1JpH6nmfG+lZ+/DCXlZ0EQ4tY5tcqy9KqKk\nnztqnqqo0m1jVqYzDhTKRPS537wsXC8vPP4Qme2/+koeQv8vJ6BlYzW4CKpJ1erc\nJZCIaPzJU0bYC9UlzYlbHQSpXjuMuKJw9yuNTdQA9XH+6Sz3fTTWxN934QKBgQCB\nsFSIZxmNtH+XLeBl6JyBLRxlQyPaq8CydUCxUwSEkEkvpeI2Xqhepx2pS3Cq5keG\nvP/HTuSw/+X0K9tOz37k2rAeZ9EYqi0XLjPZB7AioQyrDxMaWwg+aOInGXcmWFOT\nuB3DpLgUkl8Svd7r6fw0imk0DIFnlBTZ7uix5eH5MQKBgFKFTbpZ4a2TbghzjRG8\ngVDZgw9GpGNqrKffcbJg/77zJVTyQAnefyCPzzyjIw5LHPUQynA9OBTz5X/CM2/K\nachRmGPsFqMOh5om5L9uTAhcdiUjQ+WaFBsCuQJ2LA4fCJp7DPUXAQqUDfoI1mG4\nAssNuaKkiklWd1RJS0rOgugg\n-----END PRIVATE KEY-----\n"
client_email = "firebase-adminsdk-fbsvc@bhalani-55bb4.iam.gserviceaccount.com"
client_id = "112015284958601078276"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40bhalani-55bb4.iam.gserviceaccount.com"
database_url = "https://bhalani-55bb4-default-rtdb.firebaseio.com"
universe_domain = "googleapis.com"

[firebase_client]
api_key = "AIzaSyCVKlqf_11Hv5uC8E1hRvHAdRfXWkCeXEo"
auth_domain = "bhalani-55bb4.firebaseapp.com"
project_id = "bhalani-55bb4"
database_url = "https://bhalani-55bb4-default-rtdb.firebaseio.com"
storage_bucket = "bhalani-55bb4.firebasestorage.app"
messaging_sender_id = "284474094887"
app_id = "1:284474094887:web:e10947e4c48fb537376502"
measurement_id = "G-3JC64LGGTJ"
